{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4da948ce",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "from sklearn.metrics import mean_absolute_error\n",
    "\n",
    "from utils.forecasting import (\n",
    "    fit_holt_winters,\n",
    "    fit_arima,\n",
    "    fit_random_forest,\n",
    "    fit_neural_network\n",
    ")\n",
    "\n",
    "from utils.diagnostics import residual_diagnostics\n",
    "\n",
    "\n",
    "# ======================================\n",
    "# Page Config\n",
    "# ======================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title='Air Pollution Forecast Dashboard',\n",
    "    layout='wide'\n",
    ")\n",
    "\n",
    "st.title('Air Pollution Forecasting Dashboard')\n",
    "\n",
    "st.markdown(\n",
    "    '''\n",
    "    This dashboard forecasts major air pollutants using:\n",
    "\n",
    "    - Exponential Smoothing\n",
    "    - ARIMA\n",
    "    - Random Forest\n",
    "    - Neural Networks\n",
    "\n",
    "    The objective is to support environmental monitoring and public health planning.\n",
    "    '''\n",
    ")\n",
    "\n",
    "\n",
    "# ======================================\n",
    "# Load Data\n",
    "# ======================================\n",
    "\n",
    "@st.cache_data\n",
    "\n",
    "def load_data():\n",
    "\n",
    "    data = pd.read_csv('Changping_pollution.csv')\n",
    "\n",
    "    data['datetime'] = pd.to_datetime(\n",
    "        data[['year', 'month', 'day', 'hour']]\n",
    "    )\n",
    "\n",
    "    data = data.set_index('datetime')\n",
    "\n",
    "    weekly = data[['SO2', 'NO2', 'CO']].resample('W').mean()\n",
    "\n",
    "    return weekly\n",
    "\n",
    "\n",
    "\n",
    "data = load_data()\n",
    "\n",
    "\n",
    "# ======================================\n",
    "# Sidebar Controls\n",
    "# ======================================\n",
    "\n",
    "st.sidebar.header('Controls')\n",
    "\n",
    "series_name = st.sidebar.selectbox(\n",
    "    'Select Target Series',\n",
    "    ['SO2', 'NO2', 'CO']\n",
    ")\n",
    "\n",
    "model_name = st.sidebar.selectbox(\n",
    "    'Select Forecast Model',\n",
    "    ['Holt-Winters', 'ARIMA', 'Random Forest', 'Neural Network']\n",
    ")\n",
    "\n",
    "horizon = st.sidebar.slider(\n",
    "    'Forecast Horizon',\n",
    "    min_value=4,\n",
    "    max_value=52,\n",
    "    value=12\n",
    ")\n",
    "\n",
    "\n",
    "# ======================================\n",
    "# Target Series\n",
    "# ======================================\n",
    "\n",
    "series = data[series_name].dropna()\n",
    "\n",
    "split = int(len(series) * 0.8)\n",
    "\n",
    "train = series.iloc[:split]\n",
    "test = series.iloc[split:]\n",
    "\n",
    "\n",
    "# ======================================\n",
    "# Forecasting Logic\n",
    "# ======================================\n",
    "\n",
    "if model_name == 'Holt-Winters':\n",
    "\n",
    "    model, forecast, lower, upper = fit_holt_winters(\n",
    "        train,\n",
    "        horizon\n",
    "    )\n",
    "\n",
    "    residuals = model.resid\n",
    "\n",
    "elif model_name == 'ARIMA':\n",
    "\n",
    "    model, forecast, lower, upper = fit_arima(\n",
    "        train,\n",
    "        (1, 0, 0),\n",
    "        horizon\n",
    "    )\n",
    "\n",
    "    residuals = model.resid\n",
    "\n",
    "elif model_name == 'Random Forest':\n",
    "\n",
    "    model, forecast = fit_random_forest(\n",
    "        train,\n",
    "        horizon\n",
    "    )\n",
    "\n",
    "    lower = forecast - forecast.std()\n",
    "    upper = forecast + forecast.std()\n",
    "\n",
    "    residuals = pd.Series()\n",
    "\n",
    "else:\n",
    "\n",
    "    model, forecast = fit_neural_network(\n",
    "        train,\n",
    "        horizon\n",
    "    )\n",
    "\n",
    "lower = forecast - forecast.std()\n",
    "upper = forecast + forecast.std()\n",
    "\n",
    "residuals = pd.Series()\n",
    "\n",
    "\n",
    "# ======================================\n",
    "# Forecast Plot\n",
    "# ======================================\n",
    "\n",
    "fig = go.Figure()\n",
    "\n",
    "fig.add_trace(\n",
    "    go.Scatter(\n",
    "        x=train.index,\n",
    "        y=train.values,\n",
    "        mode='lines',\n",
    "        name='Training Data'\n",
    "    )\n",
    ")\n",
    "\n",
    "fig.add_trace(\n",
    "    go.Scatter(\n",
    "        x=test.index,\n",
    "        y=test.values,\n",
    "        mode='lines',\n",
    "        name='Test Data'\n",
    "    )\n",
    ")\n",
    "\n",
    "future_dates = pd.date_range(\n",
    "    start=series.index[-1],\n",
    "    periods=horizon + 1,\n",
    "    freq='W'\n",
    ")[1:]\n",
    "\n",
    "fig.add_trace(\n",
    "    go.Scatter(\n",
    "        x=future_dates,\n",
    "        y=forecast,\n",
    "        mode='lines',\n",
    "        name='Forecast'\n",
    "    )\n",
    ")\n",
    "\n",
    "fig.add_trace(\n",
    "    go.Scatter(\n",
    "        x=future_dates,\n",
    "        y=upper,\n",
    "        line=dict(width=0),\n",
    "        showlegend=False\n",
    "    )\n",
    ")\n",
    "\n",
    "fig.add_trace(\n",
    "    go.Scatter(\n",
    "        x=future_dates,\n",
    "        y=lower,\n",
    "        fill='tonexty',\n",
    "        line=dict(width=0),\n",
    "        name='95% Prediction Interval'\n",
    "    )\n",
    ")\n",
    "\n",
    "fig.update_layout(\n",
    "    title=f'{series_name} Forecast using {model_name}',\n",
    "    xaxis_title='Date',\n",
    "    yaxis_title='Pollutant Level'\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ======================================\n",
    "# Accuracy Metrics\n",
    "# ======================================\n",
    "\n",
    "st.subheader('Model Accuracy')\n",
    "\n",
    "metrics = []\n",
    "\n",
    "\n",
    "# Holt-Winters\n",
    "hw_model, hw_forecast, _, _ = fit_holt_winters(train, len(test))\n",
    "metrics.append([\n",
    "    'Holt-Winters',\n",
    "    mean_absolute_error(test, hw_forecast)\n",
    "])\n",
    "\n",
    "\n",
    "# ARIMA\n",
    "ar_model, ar_forecast, _, _ = fit_arima(train, (1, 0, 0), len(test))\n",
    "metrics.append([\n",
    "    'ARIMA',\n",
    "    mean_absolute_error(test, ar_forecast)\n",
    "])\n",
    "\n",
    "\n",
    "# Random Forest\n",
    "rf_model, rf_forecast = fit_random_forest(train, len(test))\n",
    "metrics.append([\n",
    "    'Random Forest',\n",
    "    mean_absolute_error(test.values, rf_forecast.values)\n",
    "])\n",
    "\n",
    "\n",
    "# Neural Network\n",
    "nn_model, nn_forecast = fit_neural_network(train, len(test))\n",
    "metrics.append([\n",
    "    'Neural Network',\n",
    "    mean_absolute_error(test.values, nn_forecast.values)\n",
    "])\n",
    "\n",
    "\n",
    "metrics_df = pd.DataFrame(\n",
    "    metrics,\n",
    "    columns=['Model', 'MAE']\n",
    ")\n",
    "\n",
    "st.dataframe(metrics_df)\n",
    "\n",
    "# ======================================\n",
    "# Residual Diagnostics\n",
    "# ======================================\n",
    "\n",
    "st.subheader('Residual Diagnostics')\n",
    "\n",
    "if len(residuals) > 0:\n",
    "\n",
    "    diag_fig, lb = residual_diagnostics(residuals)\n",
    "\n",
    "    st.pyplot(diag_fig)\n",
    "\n",
    "    st.write('Ljung-Box Test')\n",
    "    st.dataframe(lb)\n",
    "\n",
    "else:\n",
    "\n",
    "    st.info(\n",
    "        'Residual diagnostics are only shown for statistical models.'\n",
    "    )"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
